version: 0.4.5-rc1#{build}
image: Visual Studio 2017

build: off

clone_folder: c:\gopath\src\github.com\Fantom-foundation\go-opera

environment:
  PATH: C:\gopath\bin;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;C:\PROGRA~1\Git\bin;C:\PROGRA~1\Git\usr\bin\;C:\ProgramData\chocolatey\bin;$(PATH)
  GOPATH: c:\gopath
  GO111MODULE: on

stack: go 1.14

init:
  - choco install make mingw

cache:
  - C:\usr
  - C:\ProgramData\chocolatey

before_test:
  - ps: Set-NetFirewallProfile -All -Enabled False
  - ps: Disable-NetFirewallRule -All

test_script:
  - go test -v ./...
