// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ShortNode struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val                  *Node    `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortNode) Reset()         { *m = ShortNode{} }
func (m *ShortNode) String() string { return proto.CompactTextString(m) }
func (*ShortNode) ProtoMessage()    {}
func (*ShortNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *ShortNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortNode.Unmarshal(m, b)
}
func (m *ShortNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortNode.Marshal(b, m, deterministic)
}
func (m *ShortNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortNode.Merge(m, src)
}
func (m *ShortNode) XXX_Size() int {
	return xxx_messageInfo_ShortNode.Size(m)
}
func (m *ShortNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortNode.DiscardUnknown(m)
}

var xxx_messageInfo_ShortNode proto.InternalMessageInfo

func (m *ShortNode) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ShortNode) GetVal() *Node {
	if m != nil {
		return m.Val
	}
	return nil
}

type FullNode struct {
	Children             []*Node  `protobuf:"bytes,1,rep,name=Children,proto3" json:"Children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullNode) Reset()         { *m = FullNode{} }
func (m *FullNode) String() string { return proto.CompactTextString(m) }
func (*FullNode) ProtoMessage()    {}
func (*FullNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *FullNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullNode.Unmarshal(m, b)
}
func (m *FullNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullNode.Marshal(b, m, deterministic)
}
func (m *FullNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullNode.Merge(m, src)
}
func (m *FullNode) XXX_Size() int {
	return xxx_messageInfo_FullNode.Size(m)
}
func (m *FullNode) XXX_DiscardUnknown() {
	xxx_messageInfo_FullNode.DiscardUnknown(m)
}

var xxx_messageInfo_FullNode proto.InternalMessageInfo

func (m *FullNode) GetChildren() []*Node {
	if m != nil {
		return m.Children
	}
	return nil
}

type Node struct {
	// Types that are valid to be assigned to Kind:
	//	*Node_Short
	//	*Node_Full
	//	*Node_Hash
	//	*Node_Value
	Kind                 isNode_Kind `protobuf_oneof:"Kind"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

type isNode_Kind interface {
	isNode_Kind()
}

type Node_Short struct {
	Short *ShortNode `protobuf:"bytes,1,opt,name=Short,proto3,oneof"`
}

type Node_Full struct {
	Full *FullNode `protobuf:"bytes,2,opt,name=Full,proto3,oneof"`
}

type Node_Hash struct {
	Hash []byte `protobuf:"bytes,3,opt,name=Hash,proto3,oneof"`
}

type Node_Value struct {
	Value []byte `protobuf:"bytes,4,opt,name=Value,proto3,oneof"`
}

func (*Node_Short) isNode_Kind() {}

func (*Node_Full) isNode_Kind() {}

func (*Node_Hash) isNode_Kind() {}

func (*Node_Value) isNode_Kind() {}

func (m *Node) GetKind() isNode_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Node) GetShort() *ShortNode {
	if x, ok := m.GetKind().(*Node_Short); ok {
		return x.Short
	}
	return nil
}

func (m *Node) GetFull() *FullNode {
	if x, ok := m.GetKind().(*Node_Full); ok {
		return x.Full
	}
	return nil
}

func (m *Node) GetHash() []byte {
	if x, ok := m.GetKind().(*Node_Hash); ok {
		return x.Hash
	}
	return nil
}

func (m *Node) GetValue() []byte {
	if x, ok := m.GetKind().(*Node_Value); ok {
		return x.Value
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Node) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Node_OneofMarshaler, _Node_OneofUnmarshaler, _Node_OneofSizer, []interface{}{
		(*Node_Short)(nil),
		(*Node_Full)(nil),
		(*Node_Hash)(nil),
		(*Node_Value)(nil),
	}
}

func _Node_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Node)
	// Kind
	switch x := m.Kind.(type) {
	case *Node_Short:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Short); err != nil {
			return err
		}
	case *Node_Full:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Full); err != nil {
			return err
		}
	case *Node_Hash:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Hash)
	case *Node_Value:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Value)
	case nil:
	default:
		return fmt.Errorf("Node.Kind has unexpected type %T", x)
	}
	return nil
}

func _Node_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Node)
	switch tag {
	case 1: // Kind.Short
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ShortNode)
		err := b.DecodeMessage(msg)
		m.Kind = &Node_Short{msg}
		return true, err
	case 2: // Kind.Full
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FullNode)
		err := b.DecodeMessage(msg)
		m.Kind = &Node_Full{msg}
		return true, err
	case 3: // Kind.Hash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Kind = &Node_Hash{x}
		return true, err
	case 4: // Kind.Value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Kind = &Node_Value{x}
		return true, err
	default:
		return false, nil
	}
}

func _Node_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Node)
	// Kind
	switch x := m.Kind.(type) {
	case *Node_Short:
		s := proto.Size(x.Short)
		n++ // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Node_Full:
		s := proto.Size(x.Full)
		n++ // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Node_Hash:
		n++ // tag and wire
		n += proto.SizeVarint(uint64(len(x.Hash)))
		n += len(x.Hash)
	case *Node_Value:
		n++ // tag and wire
		n += proto.SizeVarint(uint64(len(x.Value)))
		n += len(x.Value)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ShortNode)(nil), "internal.ShortNode")
	proto.RegisterType((*FullNode)(nil), "internal.FullNode")
	proto.RegisterType((*Node)(nil), "internal.Node")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcb, 0x4f, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc,
	0x51, 0xb2, 0xe7, 0xe2, 0x0c, 0xce, 0xc8, 0x2f, 0x2a, 0xf1, 0xcb, 0x4f, 0x49, 0x15, 0x12, 0xe0,
	0x62, 0xf6, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0x31, 0x85, 0x14, 0xb8,
	0x98, 0xc3, 0x12, 0x73, 0x24, 0x98, 0x14, 0x18, 0x35, 0xb8, 0x8d, 0xf8, 0xf4, 0x60, 0xda, 0xf4,
	0x40, 0xca, 0x83, 0x40, 0x52, 0x4a, 0x66, 0x5c, 0x1c, 0x6e, 0xa5, 0x39, 0x39, 0x60, 0xfd, 0x5a,
	0x5c, 0x1c, 0xce, 0x19, 0x99, 0x39, 0x29, 0x45, 0xa9, 0x79, 0x12, 0x8c, 0x0a, 0xcc, 0x58, 0xb4,
	0xc0, 0xe5, 0x95, 0x26, 0x33, 0x72, 0xb1, 0x80, 0x35, 0x69, 0x73, 0xb1, 0x82, 0x5d, 0x00, 0xb6,
	0x96, 0xdb, 0x48, 0x18, 0xa1, 0x03, 0xee, 0x30, 0x0f, 0x86, 0x20, 0x88, 0x1a, 0x21, 0x0d, 0x2e,
	0x16, 0x90, 0x6d, 0x50, 0x07, 0x09, 0x21, 0xd4, 0xc2, 0xdc, 0xe0, 0xc1, 0x10, 0x04, 0x56, 0x21,
	0x24, 0xc2, 0xc5, 0xe2, 0x91, 0x58, 0x9c, 0x21, 0xc1, 0x0c, 0xf2, 0x0c, 0x48, 0x14, 0xc4, 0x13,
	0x12, 0xe3, 0x62, 0x0d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x81, 0x0a, 0x43, 0xb8, 0x4e, 0x6c,
	0x5c, 0x2c, 0xde, 0x99, 0x79, 0x29, 0x49, 0x6c, 0xe0, 0xf0, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xe3, 0xac, 0x05, 0x55, 0x2d, 0x01, 0x00, 0x00,
}
