// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wire_body.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WireBody struct {
	// TODO: use a better data type, for now we will cast to [][]byte
	Transactions         []string              `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	BlockSignatures      []*WireBlockSignature `protobuf:"bytes,2,rep,name=blockSignatures,proto3" json:"blockSignatures,omitempty"`
	SelfParentIndex      int32                 `protobuf:"varint,3,opt,name=selfParentIndex,proto3" json:"selfParentIndex,omitempty"`
	OtherParentCreatorID int32                 `protobuf:"varint,4,opt,name=otherParentCreatorID,proto3" json:"otherParentCreatorID,omitempty"`
	OtherParentIndex     int32                 `protobuf:"varint,5,opt,name=otherParentIndex,proto3" json:"otherParentIndex,omitempty"`
	CreatorID            int32                 `protobuf:"varint,6,opt,name=creatorID,proto3" json:"creatorID,omitempty"`
	Index                int32                 `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WireBody) Reset()         { *m = WireBody{} }
func (m *WireBody) String() string { return proto.CompactTextString(m) }
func (*WireBody) ProtoMessage()    {}
func (*WireBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_wire_body_e131b2b9afc76de1, []int{0}
}
func (m *WireBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireBody.Unmarshal(m, b)
}
func (m *WireBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireBody.Marshal(b, m, deterministic)
}
func (dst *WireBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireBody.Merge(dst, src)
}
func (m *WireBody) XXX_Size() int {
	return xxx_messageInfo_WireBody.Size(m)
}
func (m *WireBody) XXX_DiscardUnknown() {
	xxx_messageInfo_WireBody.DiscardUnknown(m)
}

var xxx_messageInfo_WireBody proto.InternalMessageInfo

func (m *WireBody) GetTransactions() []string {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *WireBody) GetBlockSignatures() []*WireBlockSignature {
	if m != nil {
		return m.BlockSignatures
	}
	return nil
}

func (m *WireBody) GetSelfParentIndex() int32 {
	if m != nil {
		return m.SelfParentIndex
	}
	return 0
}

func (m *WireBody) GetOtherParentCreatorID() int32 {
	if m != nil {
		return m.OtherParentCreatorID
	}
	return 0
}

func (m *WireBody) GetOtherParentIndex() int32 {
	if m != nil {
		return m.OtherParentIndex
	}
	return 0
}

func (m *WireBody) GetCreatorID() int32 {
	if m != nil {
		return m.CreatorID
	}
	return 0
}

func (m *WireBody) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*WireBody)(nil), "pb.WireBody")
}

func init() { proto.RegisterFile("wire_body.proto", fileDescriptor_wire_body_e131b2b9afc76de1) }

var fileDescriptor_wire_body_e131b2b9afc76de1 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0x69, 0x62, 0xaa, 0x1d, 0x85, 0xc8, 0x50, 0x24, 0x14, 0x0f, 0xa1, 0xa7, 0xe0, 0x21,
	0x87, 0xfa, 0x02, 0xa2, 0x5e, 0x7a, 0x93, 0x78, 0xf0, 0x58, 0x36, 0xc9, 0xa8, 0x8b, 0x65, 0x27,
	0xcc, 0xae, 0x68, 0x5f, 0xca, 0x67, 0x14, 0x66, 0xf1, 0x4f, 0xa3, 0xc7, 0xfd, 0x7e, 0xdf, 0x7e,
	0x87, 0x81, 0xfc, 0xcd, 0x0a, 0x6d, 0x5a, 0xee, 0x77, 0xf5, 0x20, 0x1c, 0x18, 0x93, 0xa1, 0x5d,
	0x2c, 0x22, 0xdc, 0x72, 0xf7, 0xb2, 0xf1, 0xf6, 0xc9, 0x99, 0xf0, 0x2a, 0x14, 0xf7, 0xe5, 0x47,
	0x02, 0x47, 0x0f, 0x56, 0xe8, 0x9a, 0xfb, 0x1d, 0x2e, 0xe1, 0x24, 0x88, 0x71, 0xde, 0x74, 0xc1,
	0xb2, 0xf3, 0xc5, 0xa4, 0x4c, 0xab, 0x59, 0xb3, 0xc7, 0xf0, 0x0a, 0x72, 0x2d, 0xdd, 0x7f, 0x85,
	0x7c, 0x91, 0x94, 0x69, 0x75, 0xbc, 0x3a, 0xab, 0x87, 0xb6, 0xd6, 0xd4, 0xde, 0xdc, 0x8c, 0x75,
	0xac, 0x20, 0xf7, 0xb4, 0x7d, 0xbc, 0x33, 0x42, 0x2e, 0xac, 0x5d, 0x4f, 0xef, 0x45, 0x5a, 0x4e,
	0xaa, 0xac, 0x19, 0x63, 0x5c, 0xc1, 0x9c, 0xc3, 0x33, 0x49, 0x64, 0x37, 0x42, 0x26, 0xb0, 0xac,
	0x6f, 0x8b, 0x03, 0xd5, 0xff, 0xdd, 0xf0, 0x02, 0x4e, 0x7f, 0xf1, 0x98, 0xcf, 0xd4, 0xff, 0xc3,
	0xf1, 0x1c, 0x66, 0xdd, 0x77, 0x74, 0xaa, 0xd2, 0x0f, 0xc0, 0x39, 0x64, 0x56, 0xbf, 0x1f, 0xea,
	0x12, 0x1f, 0xed, 0x54, 0xef, 0x76, 0xf9, 0x19, 0x00, 0x00, 0xff, 0xff, 0x68, 0xba, 0x9d, 0x49,
	0x6a, 0x01, 0x00, 0x00,
}
