// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InternalTransaction struct {
	Index                uint64   `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Receiver             string   `protobuf:"bytes,3,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	Sender               string   `protobuf:"bytes,4,opt,name=Sender,proto3" json:"Sender,omitempty"`
	UntilBlock           uint64   `protobuf:"varint,5,opt,name=UntilBlock,proto3" json:"UntilBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalTransaction) Reset()         { *m = InternalTransaction{} }
func (m *InternalTransaction) String() string { return proto.CompactTextString(m) }
func (*InternalTransaction) ProtoMessage()    {}
func (*InternalTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *InternalTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalTransaction.Unmarshal(m, b)
}
func (m *InternalTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalTransaction.Marshal(b, m, deterministic)
}
func (m *InternalTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalTransaction.Merge(m, src)
}
func (m *InternalTransaction) XXX_Size() int {
	return xxx_messageInfo_InternalTransaction.Size(m)
}
func (m *InternalTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_InternalTransaction proto.InternalMessageInfo

func (m *InternalTransaction) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *InternalTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InternalTransaction) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *InternalTransaction) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *InternalTransaction) GetUntilBlock() uint64 {
	if m != nil {
		return m.UntilBlock
	}
	return 0
}

type Event struct {
	Index                uint64                 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Creator              string                 `protobuf:"bytes,2,opt,name=Creator,proto3" json:"Creator,omitempty"`
	Parents              [][]byte               `protobuf:"bytes,3,rep,name=Parents,proto3" json:"Parents,omitempty"`
	LamportTime          uint64                 `protobuf:"varint,4,opt,name=LamportTime,proto3" json:"LamportTime,omitempty"`
	InternalTransactions []*InternalTransaction `protobuf:"bytes,5,rep,name=InternalTransactions,proto3" json:"InternalTransactions,omitempty"`
	ExternalTransactions [][]byte               `protobuf:"bytes,6,rep,name=ExternalTransactions,proto3" json:"ExternalTransactions,omitempty"`
	Sign                 string                 `protobuf:"bytes,7,opt,name=Sign,proto3" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Event) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Event) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *Event) GetLamportTime() uint64 {
	if m != nil {
		return m.LamportTime
	}
	return 0
}

func (m *Event) GetInternalTransactions() []*InternalTransaction {
	if m != nil {
		return m.InternalTransactions
	}
	return nil
}

func (m *Event) GetExternalTransactions() [][]byte {
	if m != nil {
		return m.ExternalTransactions
	}
	return nil
}

func (m *Event) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func init() {
	proto.RegisterType((*InternalTransaction)(nil), "wire.InternalTransaction")
	proto.RegisterType((*Event)(nil), "wire.Event")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4e, 0xc3, 0x30,
	0x0c, 0x86, 0xd5, 0xb5, 0xdd, 0x98, 0xcb, 0xc9, 0x54, 0x28, 0x70, 0x40, 0xd5, 0x4e, 0x3d, 0xf5,
	0x30, 0x9e, 0x00, 0xd0, 0x0e, 0x93, 0x40, 0x42, 0xd9, 0x78, 0x80, 0xd0, 0x59, 0x28, 0xa2, 0x75,
	0x26, 0x37, 0x8c, 0x3d, 0x03, 0x2f, 0xc0, 0xeb, 0xa2, 0x86, 0x0d, 0xed, 0x50, 0x6e, 0xf9, 0xfc,
	0xc7, 0xd6, 0x17, 0x07, 0x32, 0xda, 0x11, 0xfb, 0x6a, 0x2b, 0xce, 0x3b, 0x4c, 0x3e, 0xad, 0xd0,
	0xec, 0x3b, 0x82, 0x8b, 0x25, 0x7b, 0x12, 0x36, 0xcd, 0x5a, 0x0c, 0x77, 0xa6, 0xf6, 0xd6, 0x31,
	0xe6, 0x90, 0x2e, 0x79, 0x43, 0x7b, 0x15, 0x15, 0x51, 0x99, 0xe8, 0x5f, 0xc0, 0x4b, 0x18, 0xdf,
	0xb5, 0xee, 0x83, 0xbd, 0x1a, 0x85, 0xf2, 0x81, 0xf0, 0x1a, 0xce, 0x34, 0xd5, 0x64, 0x77, 0x24,
	0x2a, 0x2e, 0xa2, 0x72, 0xaa, 0xff, 0xb8, 0xef, 0x59, 0x11, 0x6f, 0x48, 0x54, 0x12, 0x92, 0x03,
	0xe1, 0x0d, 0xc0, 0x0b, 0x7b, 0xdb, 0xdc, 0x37, 0xae, 0x7e, 0x57, 0x69, 0x98, 0x77, 0x52, 0x99,
	0x7d, 0x8d, 0x20, 0x5d, 0xf4, 0xbe, 0xff, 0xb8, 0x28, 0x98, 0x3c, 0x08, 0x19, 0xef, 0x24, 0xc8,
	0x4c, 0xf5, 0x11, 0xfb, 0xe4, 0xd9, 0x08, 0xb1, 0xef, 0x54, 0x5c, 0xc4, 0xe5, 0xb9, 0x3e, 0x22,
	0x16, 0x90, 0x3d, 0x9a, 0x76, 0xeb, 0xc4, 0xaf, 0x6d, 0x4b, 0x41, 0x28, 0xd1, 0xa7, 0x25, 0x7c,
	0x82, 0x7c, 0x60, 0x1d, 0x9d, 0x4a, 0x8b, 0xb8, 0xcc, 0xe6, 0x57, 0x55, 0xbf, 0xb4, 0x6a, 0xe0,
	0x86, 0x1e, 0x6c, 0xc3, 0x39, 0xe4, 0x8b, 0xfd, 0xc0, 0xb8, 0x71, 0xf0, 0x1a, 0xcc, 0x10, 0x21,
	0x59, 0xd9, 0x37, 0x56, 0x93, 0xf0, 0xaa, 0x70, 0x7e, 0x1d, 0x87, 0x3f, 0xbb, 0xfd, 0x09, 0x00,
	0x00, 0xff, 0xff, 0xd9, 0x7d, 0x6c, 0xa6, 0xc2, 0x01, 0x00, 0x00,
}
