// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frame.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventDescr struct {
	Creator              []byte   `protobuf:"bytes,1,opt,name=Creator,json=creator,proto3" json:"Creator,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=Hash,json=hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDescr) Reset()         { *m = EventDescr{} }
func (m *EventDescr) String() string { return proto.CompactTextString(m) }
func (*EventDescr) ProtoMessage()    {}
func (*EventDescr) Descriptor() ([]byte, []int) {
	return fileDescriptor_5379e2b825e15002, []int{0}
}

func (m *EventDescr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDescr.Unmarshal(m, b)
}
func (m *EventDescr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDescr.Marshal(b, m, deterministic)
}
func (m *EventDescr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDescr.Merge(m, src)
}
func (m *EventDescr) XXX_Size() int {
	return xxx_messageInfo_EventDescr.Size(m)
}
func (m *EventDescr) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDescr.DiscardUnknown(m)
}

var xxx_messageInfo_EventDescr proto.InternalMessageInfo

func (m *EventDescr) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *EventDescr) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Flag struct {
	Event                []byte        `protobuf:"bytes,1,opt,name=Event,json=event,proto3" json:"Event,omitempty"`
	Roots                []*EventDescr `protobuf:"bytes,2,rep,name=Roots,json=roots,proto3" json:"Roots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Flag) Reset()         { *m = Flag{} }
func (m *Flag) String() string { return proto.CompactTextString(m) }
func (*Flag) ProtoMessage()    {}
func (*Flag) Descriptor() ([]byte, []int) {
	return fileDescriptor_5379e2b825e15002, []int{1}
}

func (m *Flag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flag.Unmarshal(m, b)
}
func (m *Flag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flag.Marshal(b, m, deterministic)
}
func (m *Flag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flag.Merge(m, src)
}
func (m *Flag) XXX_Size() int {
	return xxx_messageInfo_Flag.Size(m)
}
func (m *Flag) XXX_DiscardUnknown() {
	xxx_messageInfo_Flag.DiscardUnknown(m)
}

var xxx_messageInfo_Flag proto.InternalMessageInfo

func (m *Flag) GetEvent() []byte {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Flag) GetRoots() []*EventDescr {
	if m != nil {
		return m.Roots
	}
	return nil
}

type Frame struct {
	Index                uint32        `protobuf:"varint,1,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	FlagTable            []*Flag       `protobuf:"bytes,2,rep,name=FlagTable,json=flagTable,proto3" json:"FlagTable,omitempty"`
	ClothoCandidates     []*EventDescr `protobuf:"bytes,3,rep,name=ClothoCandidates,json=clothoCandidates,proto3" json:"ClothoCandidates,omitempty"`
	Balances             []byte        `protobuf:"bytes,4,opt,name=Balances,json=balances,proto3" json:"Balances,omitempty"`
	TimeOffset           uint64        `protobuf:"varint,5,opt,name=timeOffset,proto3" json:"timeOffset,omitempty"`
	TimeRatio            uint64        `protobuf:"varint,6,opt,name=timeRatio,proto3" json:"timeRatio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_5379e2b825e15002, []int{2}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Frame) GetFlagTable() []*Flag {
	if m != nil {
		return m.FlagTable
	}
	return nil
}

func (m *Frame) GetClothoCandidates() []*EventDescr {
	if m != nil {
		return m.ClothoCandidates
	}
	return nil
}

func (m *Frame) GetBalances() []byte {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *Frame) GetTimeOffset() uint64 {
	if m != nil {
		return m.TimeOffset
	}
	return 0
}

func (m *Frame) GetTimeRatio() uint64 {
	if m != nil {
		return m.TimeRatio
	}
	return 0
}

func init() {
	proto.RegisterType((*EventDescr)(nil), "wire.EventDescr")
	proto.RegisterType((*Flag)(nil), "wire.Flag")
	proto.RegisterType((*Frame)(nil), "wire.Frame")
}

func init() { proto.RegisterFile("frame.proto", fileDescriptor_5379e2b825e15002) }

var fileDescriptor_5379e2b825e15002 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0xe9, 0x4c, 0x32, 0x3f, 0x77, 0x14, 0x86, 0x8b, 0x8b, 0x20, 0x22, 0x43, 0x17, 0xd2,
	0x55, 0x17, 0xba, 0x13, 0x57, 0x76, 0x1c, 0x74, 0x25, 0x04, 0x5f, 0xe0, 0xb6, 0xbd, 0xb5, 0x85,
	0x4e, 0x23, 0x49, 0x50, 0xdf, 0xd6, 0x57, 0x91, 0x64, 0x2a, 0x23, 0x82, 0xcb, 0xef, 0x9c, 0xf6,
	0x3b, 0x49, 0x60, 0xd5, 0x58, 0xda, 0x73, 0xfe, 0x66, 0x8d, 0x37, 0x28, 0x3e, 0x3a, 0xcb, 0xe9,
	0x2d, 0xc0, 0xc3, 0x3b, 0x0f, 0x7e, 0xcb, 0xae, 0xb2, 0xa8, 0x60, 0x5e, 0x58, 0x26, 0x6f, 0xac,
	0x4a, 0x36, 0x49, 0x76, 0xa2, 0xe7, 0xd5, 0x01, 0x11, 0x41, 0x3c, 0x92, 0x6b, 0xd5, 0x24, 0xc6,
	0xa2, 0x25, 0xd7, 0xa6, 0x5b, 0x10, 0xbb, 0x9e, 0x5e, 0xf1, 0x0c, 0x64, 0x74, 0x8c, 0xff, 0x48,
	0x0e, 0x80, 0x57, 0x20, 0xb5, 0x31, 0xde, 0xa9, 0xc9, 0x66, 0x9a, 0xad, 0xae, 0xd7, 0x79, 0xd8,
	0xcb, 0x8f, 0x63, 0x5a, 0xda, 0x50, 0xa7, 0x5f, 0x09, 0xc8, 0x5d, 0x38, 0x57, 0xf0, 0x3c, 0x0d,
	0x35, 0x7f, 0x46, 0xcf, 0xa9, 0x96, 0x5d, 0x00, 0xcc, 0x60, 0x19, 0x56, 0x5e, 0xa8, 0xec, 0x79,
	0x74, 0xc1, 0xc1, 0x15, 0x62, 0xbd, 0x6c, 0x7e, 0x4a, 0xbc, 0x83, 0x75, 0xd1, 0x1b, 0xdf, 0x9a,
	0x82, 0x86, 0xba, 0xab, 0xc9, 0xb3, 0x53, 0xd3, 0x7f, 0xc6, 0xd7, 0xd5, 0x9f, 0x2f, 0xf1, 0x1c,
	0x16, 0xf7, 0xd4, 0xd3, 0x50, 0xb1, 0x53, 0x22, 0x5e, 0x64, 0x51, 0x8e, 0x8c, 0x97, 0x00, 0xbe,
	0xdb, 0xf3, 0x73, 0xd3, 0x38, 0xf6, 0x4a, 0x6e, 0x92, 0x4c, 0xe8, 0x5f, 0x09, 0x5e, 0xc0, 0x32,
	0x90, 0x26, 0xdf, 0x19, 0x35, 0x8b, 0xf5, 0x31, 0x28, 0x67, 0xf1, 0xc1, 0x6f, 0xbe, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x67, 0x30, 0xbe, 0x4d, 0x7f, 0x01, 0x00, 0x00,
}
