// Code generated by protoc-gen-go. DO NOT EDIT.
// source: superframe.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SuperFrame struct {
	Balances             []byte            `protobuf:"bytes,1,opt,name=Balances,proto3" json:"Balances,omitempty"`
	Members              map[string]uint64 `protobuf:"bytes,2,rep,name=Members,proto3" json:"Members,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SuperFrame) Reset()         { *m = SuperFrame{} }
func (m *SuperFrame) String() string { return proto.CompactTextString(m) }
func (*SuperFrame) ProtoMessage()    {}
func (*SuperFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0545af6105faa94, []int{0}
}

func (m *SuperFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperFrame.Unmarshal(m, b)
}
func (m *SuperFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperFrame.Marshal(b, m, deterministic)
}
func (m *SuperFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperFrame.Merge(m, src)
}
func (m *SuperFrame) XXX_Size() int {
	return xxx_messageInfo_SuperFrame.Size(m)
}
func (m *SuperFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SuperFrame proto.InternalMessageInfo

func (m *SuperFrame) GetBalances() []byte {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *SuperFrame) GetMembers() map[string]uint64 {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*SuperFrame)(nil), "wire.SuperFrame")
	proto.RegisterMapType((map[string]uint64)(nil), "wire.SuperFrame.MembersEntry")
}

func init() { proto.RegisterFile("superframe.proto", fileDescriptor_e0545af6105faa94) }

var fileDescriptor_e0545af6105faa94 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2e, 0x2d, 0x48,
	0x2d, 0x4a, 0x2b, 0x4a, 0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0xcf,
	0x2c, 0x4a, 0x55, 0x9a, 0xcb, 0xc8, 0xc5, 0x15, 0x0c, 0x92, 0x72, 0x03, 0x49, 0x09, 0x49, 0x71,
	0x71, 0x38, 0x25, 0xe6, 0x24, 0xe6, 0x25, 0xa7, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04,
	0xc1, 0xf9, 0x42, 0xe6, 0x5c, 0xec, 0xbe, 0xa9, 0xb9, 0x49, 0xa9, 0x45, 0xc5, 0x12, 0x4c, 0x0a,
	0xcc, 0x1a, 0xdc, 0x46, 0xb2, 0x7a, 0x20, 0x23, 0xf4, 0x10, 0xda, 0xf5, 0xa0, 0xf2, 0xae, 0x79,
	0x25, 0x45, 0x95, 0x41, 0x30, 0xd5, 0x52, 0x56, 0x5c, 0x3c, 0xc8, 0x12, 0x42, 0x02, 0x5c, 0xcc,
	0xd9, 0xa9, 0x95, 0x60, 0xf3, 0x39, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c,
	0xd2, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x08, 0xc7, 0x8a, 0xc9, 0x82, 0x31, 0x89,
	0x0d, 0xec, 0x58, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x81, 0xf8, 0x9f, 0xc0, 0x00,
	0x00, 0x00,
}
