FROM golang:alpine3.19 as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

WORKDIR /go/go-x1
COPY . .

ARG GOPROXY
RUN go mod download
RUN make x1



FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /go/go-x1/build/x1 /

EXPOSE 5050 8545 8546

ENTRYPOINT ["/x1"]
