// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package api

import (
	fmt "fmt"
	wire "github.com/Fantom-foundation/go-lachesis/src/inter/wire"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KnownEvents struct {
	SuperFrameN          uint64            `protobuf:"varint,1,opt,name=SuperFrameN,proto3" json:"SuperFrameN,omitempty"`
	Lasts                map[string]uint64 `protobuf:"bytes,2,rep,name=Lasts,proto3" json:"Lasts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *KnownEvents) Reset()         { *m = KnownEvents{} }
func (m *KnownEvents) String() string { return proto.CompactTextString(m) }
func (*KnownEvents) ProtoMessage()    {}
func (*KnownEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *KnownEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KnownEvents.Unmarshal(m, b)
}
func (m *KnownEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KnownEvents.Marshal(b, m, deterministic)
}
func (m *KnownEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KnownEvents.Merge(m, src)
}
func (m *KnownEvents) XXX_Size() int {
	return xxx_messageInfo_KnownEvents.Size(m)
}
func (m *KnownEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_KnownEvents.DiscardUnknown(m)
}

var xxx_messageInfo_KnownEvents proto.InternalMessageInfo

func (m *KnownEvents) GetSuperFrameN() uint64 {
	if m != nil {
		return m.SuperFrameN
	}
	return 0
}

func (m *KnownEvents) GetLasts() map[string]uint64 {
	if m != nil {
		return m.Lasts
	}
	return nil
}

type EventRequest struct {
	PeerID               string   `protobuf:"bytes,1,opt,name=PeerID,proto3" json:"PeerID,omitempty"`
	SuperFrameN          uint64   `protobuf:"varint,2,opt,name=SuperFrameN,proto3" json:"SuperFrameN,omitempty"`
	Seq                  uint64   `protobuf:"varint,3,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Hash                 []byte   `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *EventRequest) GetSuperFrameN() uint64 {
	if m != nil {
		return m.SuperFrameN
	}
	return 0
}

func (m *EventRequest) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *EventRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type PeerRequest struct {
	PeerID               string   `protobuf:"bytes,1,opt,name=PeerID,proto3" json:"PeerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerRequest) Reset()         { *m = PeerRequest{} }
func (m *PeerRequest) String() string { return proto.CompactTextString(m) }
func (*PeerRequest) ProtoMessage()    {}
func (*PeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *PeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerRequest.Unmarshal(m, b)
}
func (m *PeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerRequest.Marshal(b, m, deterministic)
}
func (m *PeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerRequest.Merge(m, src)
}
func (m *PeerRequest) XXX_Size() int {
	return xxx_messageInfo_PeerRequest.Size(m)
}
func (m *PeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerRequest proto.InternalMessageInfo

func (m *PeerRequest) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

type PeerInfo struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=Host,proto3" json:"Host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (m *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(m, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PeerInfo) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *PeerInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func init() {
	proto.RegisterType((*KnownEvents)(nil), "api.KnownEvents")
	proto.RegisterMapType((map[string]uint64)(nil), "api.KnownEvents.LastsEntry")
	proto.RegisterType((*EventRequest)(nil), "api.EventRequest")
	proto.RegisterType((*PeerRequest)(nil), "api.PeerRequest")
	proto.RegisterType((*PeerInfo)(nil), "api.PeerInfo")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcb, 0x4e, 0xf2, 0x40,
	0x14, 0xa6, 0x17, 0x08, 0x9c, 0xc2, 0x1f, 0xfe, 0x89, 0x9a, 0xa6, 0x6e, 0x9a, 0x26, 0x26, 0x2c,
	0x4c, 0x55, 0xdc, 0x10, 0xd7, 0x5c, 0x24, 0x18, 0x62, 0x86, 0x27, 0x28, 0x78, 0x8c, 0x8d, 0x3a,
	0x2d, 0x33, 0x53, 0x48, 0x5f, 0xc5, 0xf8, 0xb0, 0xa6, 0xa7, 0x0d, 0x36, 0xb0, 0x70, 0xd3, 0x7c,
	0x97, 0x99, 0xef, 0x7c, 0x9d, 0x19, 0xe8, 0x29, 0x94, 0xbb, 0x78, 0x83, 0x61, 0x2a, 0x13, 0x9d,
	0x30, 0x2b, 0x4a, 0x63, 0xef, 0x3c, 0x16, 0x1a, 0xe5, 0xcd, 0x3e, 0x96, 0x48, 0x9f, 0xd2, 0x0b,
	0xbe, 0x0d, 0x70, 0x16, 0x22, 0xd9, 0x8b, 0xc9, 0x0e, 0x85, 0x56, 0xcc, 0x07, 0x67, 0x95, 0xa5,
	0x28, 0xa7, 0x32, 0xfa, 0xc4, 0xa5, 0x6b, 0xf8, 0xc6, 0xc0, 0xe6, 0x75, 0x89, 0xdd, 0x41, 0xf3,
	0x29, 0x52, 0x5a, 0xb9, 0xa6, 0x6f, 0x0d, 0x9c, 0xe1, 0x65, 0x18, 0xa5, 0x71, 0x58, 0x8b, 0x08,
	0xc9, 0x9d, 0x08, 0x2d, 0x73, 0x5e, 0xae, 0xf4, 0x46, 0x00, 0xbf, 0x22, 0xeb, 0x83, 0xf5, 0x8e,
	0x39, 0x45, 0x77, 0x78, 0x01, 0xd9, 0x19, 0x34, 0x77, 0xd1, 0x47, 0x86, 0xae, 0x49, 0xe3, 0x4a,
	0xf2, 0x60, 0x8e, 0x8c, 0x40, 0x40, 0x97, 0x52, 0x39, 0x6e, 0x33, 0x54, 0x9a, 0x5d, 0x40, 0xeb,
	0x19, 0x51, 0xce, 0xc7, 0xd5, 0xf6, 0x8a, 0x1d, 0xd7, 0x36, 0x4f, 0x6b, 0xf7, 0xc1, 0x5a, 0xe1,
	0xd6, 0xb5, 0xc8, 0x29, 0x20, 0x63, 0x60, 0x3f, 0x46, 0xea, 0xcd, 0xb5, 0x7d, 0x63, 0xd0, 0xe5,
	0x84, 0x83, 0x2b, 0x70, 0x8a, 0xc4, 0x3f, 0xc6, 0x05, 0x53, 0x68, 0x13, 0x12, 0xaf, 0x09, 0xfb,
	0x07, 0xe6, 0xc1, 0x37, 0xe7, 0x63, 0xda, 0x93, 0xad, 0x17, 0x98, 0x53, 0x8b, 0x2e, 0xaf, 0x18,
	0x8d, 0x4b, 0x94, 0xa6, 0x06, 0x1d, 0x4e, 0x78, 0xf8, 0x65, 0x80, 0xbd, 0x4c, 0x5e, 0x90, 0x0d,
	0x01, 0x56, 0xb9, 0xd8, 0x54, 0x97, 0xd0, 0x3f, 0x3e, 0x53, 0xef, 0x44, 0x09, 0x1a, 0xec, 0x1a,
	0xda, 0x33, 0xd4, 0x44, 0xd9, 0x7f, 0xf2, 0xeb, 0x47, 0xe5, 0x39, 0x21, 0x5d, 0x33, 0x69, 0x41,
	0x83, 0xdd, 0x82, 0x33, 0x43, 0x7d, 0x68, 0x5d, 0x06, 0xd6, 0xfe, 0xd5, 0xeb, 0x1d, 0x94, 0x62,
	0x41, 0xd0, 0x58, 0xb7, 0xe8, 0x85, 0xdc, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x65, 0x3f, 0x64,
	0xf8, 0x4e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	SyncEvents(ctx context.Context, in *KnownEvents, opts ...grpc.CallOption) (*KnownEvents, error)
	GetEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*wire.Event, error)
	GetPeerInfo(ctx context.Context, in *PeerRequest, opts ...grpc.CallOption) (*PeerInfo, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) SyncEvents(ctx context.Context, in *KnownEvents, opts ...grpc.CallOption) (*KnownEvents, error) {
	out := new(KnownEvents)
	err := c.cc.Invoke(ctx, "/api.Node/SyncEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*wire.Event, error) {
	out := new(wire.Event)
	err := c.cc.Invoke(ctx, "/api.Node/GetEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetPeerInfo(ctx context.Context, in *PeerRequest, opts ...grpc.CallOption) (*PeerInfo, error) {
	out := new(PeerInfo)
	err := c.cc.Invoke(ctx, "/api.Node/GetPeerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	SyncEvents(context.Context, *KnownEvents) (*KnownEvents, error)
	GetEvent(context.Context, *EventRequest) (*wire.Event, error)
	GetPeerInfo(context.Context, *PeerRequest) (*PeerInfo, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_SyncEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnownEvents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SyncEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/SyncEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SyncEvents(ctx, req.(*KnownEvents))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/GetEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetPeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetPeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/GetPeerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetPeerInfo(ctx, req.(*PeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncEvents",
			Handler:    _Node_SyncEvents_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _Node_GetEvent_Handler,
		},
		{
			MethodName: "GetPeerInfo",
			Handler:    _Node_GetPeerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
