// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package poset

import (
	fmt "fmt"
	wire "github.com/Fantom-foundation/go-lachesis/src/inter/wire"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockSignature struct {
	Validator            []byte   `protobuf:"bytes,1,opt,name=Validator,proto3" json:"Validator,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSignature) Reset()         { *m = BlockSignature{} }
func (m *BlockSignature) String() string { return proto.CompactTextString(m) }
func (*BlockSignature) ProtoMessage()    {}
func (*BlockSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *BlockSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSignature.Unmarshal(m, b)
}
func (m *BlockSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSignature.Marshal(b, m, deterministic)
}
func (m *BlockSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSignature.Merge(m, src)
}
func (m *BlockSignature) XXX_Size() int {
	return xxx_messageInfo_BlockSignature.Size(m)
}
func (m *BlockSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSignature.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSignature proto.InternalMessageInfo

func (m *BlockSignature) GetValidator() []byte {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *BlockSignature) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BlockSignature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type EventBody struct {
	Transactions         [][]byte                    `protobuf:"bytes,1,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	InternalTransactions []*wire.InternalTransaction `protobuf:"bytes,2,rep,name=InternalTransactions,proto3" json:"InternalTransactions,omitempty"`
	Parents              [][]byte                    `protobuf:"bytes,3,rep,name=Parents,proto3" json:"Parents,omitempty"`
	Creator              []byte                      `protobuf:"bytes,4,opt,name=Creator,proto3" json:"Creator,omitempty"`
	Index                int64                       `protobuf:"varint,5,opt,name=Index,proto3" json:"Index,omitempty"`
	BlockSignatures      []*BlockSignature           `protobuf:"bytes,6,rep,name=BlockSignatures,proto3" json:"BlockSignatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *EventBody) Reset()         { *m = EventBody{} }
func (m *EventBody) String() string { return proto.CompactTextString(m) }
func (*EventBody) ProtoMessage()    {}
func (*EventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *EventBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventBody.Unmarshal(m, b)
}
func (m *EventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventBody.Marshal(b, m, deterministic)
}
func (m *EventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBody.Merge(m, src)
}
func (m *EventBody) XXX_Size() int {
	return xxx_messageInfo_EventBody.Size(m)
}
func (m *EventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBody.DiscardUnknown(m)
}

var xxx_messageInfo_EventBody proto.InternalMessageInfo

func (m *EventBody) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *EventBody) GetInternalTransactions() []*wire.InternalTransaction {
	if m != nil {
		return m.InternalTransactions
	}
	return nil
}

func (m *EventBody) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *EventBody) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *EventBody) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *EventBody) GetBlockSignatures() []*BlockSignature {
	if m != nil {
		return m.BlockSignatures
	}
	return nil
}

type EventMessage struct {
	Body                 *EventBody `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	Signature            string     `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	FlagTable            []byte     `protobuf:"bytes,3,opt,name=FlagTable,proto3" json:"FlagTable,omitempty"`
	ClothoProof          [][]byte   `protobuf:"bytes,4,rep,name=ClothoProof,proto3" json:"ClothoProof,omitempty"`
	SelfParentIndex      int64      `protobuf:"varint,5,opt,name=SelfParentIndex,proto3" json:"SelfParentIndex,omitempty"`
	OtherParentCreatorID uint64     `protobuf:"varint,6,opt,name=OtherParentCreatorID,proto3" json:"OtherParentCreatorID,omitempty"`
	OtherParentIndex     int64      `protobuf:"varint,7,opt,name=OtherParentIndex,proto3" json:"OtherParentIndex,omitempty"`
	CreatorID            uint64     `protobuf:"varint,8,opt,name=CreatorID,proto3" json:"CreatorID,omitempty"`
	TopologicalIndex     int64      `protobuf:"varint,9,opt,name=TopologicalIndex,proto3" json:"TopologicalIndex,omitempty"`
	Hash                 []byte     `protobuf:"bytes,10,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EventMessage) Reset()         { *m = EventMessage{} }
func (m *EventMessage) String() string { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()    {}
func (*EventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *EventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventMessage.Unmarshal(m, b)
}
func (m *EventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventMessage.Marshal(b, m, deterministic)
}
func (m *EventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMessage.Merge(m, src)
}
func (m *EventMessage) XXX_Size() int {
	return xxx_messageInfo_EventMessage.Size(m)
}
func (m *EventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventMessage proto.InternalMessageInfo

func (m *EventMessage) GetBody() *EventBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *EventMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *EventMessage) GetFlagTable() []byte {
	if m != nil {
		return m.FlagTable
	}
	return nil
}

func (m *EventMessage) GetClothoProof() [][]byte {
	if m != nil {
		return m.ClothoProof
	}
	return nil
}

func (m *EventMessage) GetSelfParentIndex() int64 {
	if m != nil {
		return m.SelfParentIndex
	}
	return 0
}

func (m *EventMessage) GetOtherParentCreatorID() uint64 {
	if m != nil {
		return m.OtherParentCreatorID
	}
	return 0
}

func (m *EventMessage) GetOtherParentIndex() int64 {
	if m != nil {
		return m.OtherParentIndex
	}
	return 0
}

func (m *EventMessage) GetCreatorID() uint64 {
	if m != nil {
		return m.CreatorID
	}
	return 0
}

func (m *EventMessage) GetTopologicalIndex() int64 {
	if m != nil {
		return m.TopologicalIndex
	}
	return 0
}

func (m *EventMessage) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockSignature)(nil), "poset.BlockSignature")
	proto.RegisterType((*EventBody)(nil), "poset.EventBody")
	proto.RegisterType((*EventMessage)(nil), "poset.EventMessage")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0xf1, 0x9f, 0xa4, 0xf3, 0x89, 0x59, 0x8b, 0xc8, 0x40, 0x1b, 0xbb, 0x30, 0x61, 0x17,
	0x66, 0x50, 0x1b, 0xb2, 0x07, 0x18, 0xa4, 0x5b, 0x59, 0x2e, 0xca, 0x8a, 0x1a, 0x76, 0xaf, 0x38,
	0x8a, 0x6d, 0xa6, 0xea, 0x04, 0x49, 0xd9, 0x9f, 0x47, 0xd8, 0x2b, 0xef, 0x6a, 0x58, 0x6a, 0xe3,
	0x38, 0xcb, 0x8d, 0xf1, 0xf9, 0xce, 0xd1, 0xe7, 0xf3, 0xfd, 0x2c, 0x98, 0x88, 0x1f, 0x42, 0xd9,
	0x62, 0xa7, 0xd1, 0x22, 0x19, 0xed, 0xd0, 0x08, 0xfb, 0x66, 0x51, 0xb7, 0xb6, 0xd9, 0xaf, 0x8b,
	0x0a, 0x1f, 0xcb, 0x5b, 0xae, 0x2c, 0x3e, 0x5e, 0x6f, 0x71, 0xaf, 0x36, 0xdc, 0xb6, 0xa8, 0xca,
	0x1a, 0xaf, 0x25, 0xaf, 0x1a, 0x61, 0x5a, 0x53, 0x1a, 0x5d, 0x95, 0xad, 0xb2, 0x42, 0x97, 0x3f,
	0x5b, 0x2d, 0xdc, 0xc3, 0x5b, 0xcd, 0xd6, 0xf0, 0x72, 0x21, 0xb1, 0xfa, 0xfe, 0xd0, 0xd6, 0x8a,
	0xdb, 0xbd, 0x16, 0xe4, 0x2d, 0x24, 0xdf, 0xb8, 0x6c, 0x37, 0xdc, 0xa2, 0xa6, 0x41, 0x16, 0xe4,
	0x29, 0xeb, 0x05, 0x32, 0x85, 0xd1, 0x52, 0x6d, 0xc4, 0x2f, 0x1a, 0x66, 0x41, 0x1e, 0x31, 0x5f,
	0x74, 0x67, 0x0e, 0x06, 0x34, 0xca, 0x82, 0x3c, 0x61, 0xbd, 0x30, 0xfb, 0x13, 0x42, 0xf2, 0xb9,
	0x5b, 0x7f, 0x81, 0x9b, 0xdf, 0x64, 0x06, 0xe9, 0x4a, 0x73, 0x65, 0x78, 0xd5, 0xad, 0x69, 0x68,
	0x90, 0x45, 0x79, 0xca, 0x06, 0x1a, 0xb9, 0x83, 0xe9, 0xb2, 0x5b, 0x57, 0x71, 0x39, 0x98, 0x0d,
	0xb3, 0x28, 0x9f, 0xcc, 0x5f, 0x17, 0x2e, 0xc0, 0x99, 0x09, 0x76, 0xf6, 0x18, 0xa1, 0x70, 0x71,
	0xcf, 0xb5, 0x50, 0xd6, 0xd0, 0xc8, 0x7d, 0xed, 0xb9, 0xec, 0x3a, 0x37, 0x5a, 0xb8, 0xa8, 0xb1,
	0x8b, 0xfa, 0x5c, 0xf6, 0x41, 0x47, 0xc7, 0x41, 0x3f, 0xc2, 0xe5, 0x10, 0x97, 0xa1, 0x63, 0xb7,
	0xd3, 0xab, 0xc2, 0xfd, 0x93, 0x62, 0xd8, 0x65, 0xa7, 0xd3, 0xb3, 0xbf, 0x21, 0xa4, 0x8e, 0xc5,
	0x9d, 0x30, 0x86, 0xd7, 0x82, 0xbc, 0x83, 0xb8, 0xc3, 0xe2, 0x48, 0x4f, 0xe6, 0x57, 0x4f, 0x36,
	0x07, 0x5c, 0xcc, 0x75, 0x87, 0x80, 0xc3, 0x13, 0xc0, 0x5d, 0xf7, 0x56, 0xf2, 0x7a, 0xc5, 0xd7,
	0xd2, 0xe3, 0x4f, 0x59, 0x2f, 0x90, 0x0c, 0x26, 0x37, 0x12, 0x6d, 0x83, 0xf7, 0x1a, 0x71, 0x4b,
	0x63, 0x47, 0xe0, 0x58, 0x22, 0x39, 0x5c, 0x3e, 0x08, 0xb9, 0xf5, 0x50, 0x8e, 0x53, 0x9f, 0xca,
	0x64, 0x0e, 0xd3, 0xaf, 0xb6, 0x11, 0xda, 0x6b, 0x4f, 0xac, 0x96, 0x9f, 0xe8, 0x38, 0x0b, 0xf2,
	0x98, 0x9d, 0xed, 0x91, 0xf7, 0x70, 0x75, 0xa4, 0x7b, 0xfb, 0x0b, 0x67, 0xff, 0x9f, 0xde, 0x25,
	0xe9, 0x4d, 0x5f, 0x38, 0xd3, 0x64, 0xe0, 0xb4, 0xc2, 0x1d, 0x4a, 0xac, 0xdb, 0x8a, 0x4b, 0xef,
	0x94, 0x78, 0xa7, 0x53, 0x9d, 0x10, 0x88, 0xbf, 0x70, 0xd3, 0x50, 0x70, 0x38, 0xdc, 0xfb, 0x7a,
	0xec, 0xee, 0xfc, 0x87, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x84, 0xd9, 0x25, 0x4d, 0x03,
	0x00, 0x00,
}
