// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roundInfo.proto

package poset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Trilean int32

const (
	Trilean_UNDEFINED Trilean = 0
	Trilean_TRUE      Trilean = 1
	Trilean_FALSE     Trilean = 2
)

var Trilean_name = map[int32]string{
	0: "UNDEFINED",
	1: "TRUE",
	2: "FALSE",
}

var Trilean_value = map[string]int32{
	"UNDEFINED": 0,
	"TRUE":      1,
	"FALSE":     2,
}

func (x Trilean) String() string {
	return proto.EnumName(Trilean_name, int32(x))
}

func (Trilean) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_06add9379b5a2b9a, []int{0}
}

type RoundEvent struct {
	Consensus            bool     `protobuf:"varint,1,opt,name=Consensus,proto3" json:"Consensus,omitempty"`
	Clotho               bool     `protobuf:"varint,2,opt,name=Clotho,proto3" json:"Clotho,omitempty"`
	Atropos              Trilean  `protobuf:"varint,3,opt,name=Atropos,proto3,enum=poset.Trilean" json:"Atropos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoundEvent) Reset()         { *m = RoundEvent{} }
func (m *RoundEvent) String() string { return proto.CompactTextString(m) }
func (*RoundEvent) ProtoMessage()    {}
func (*RoundEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_06add9379b5a2b9a, []int{0}
}

func (m *RoundEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundEvent.Unmarshal(m, b)
}
func (m *RoundEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundEvent.Marshal(b, m, deterministic)
}
func (m *RoundEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundEvent.Merge(m, src)
}
func (m *RoundEvent) XXX_Size() int {
	return xxx_messageInfo_RoundEvent.Size(m)
}
func (m *RoundEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RoundEvent proto.InternalMessageInfo

func (m *RoundEvent) GetConsensus() bool {
	if m != nil {
		return m.Consensus
	}
	return false
}

func (m *RoundEvent) GetClotho() bool {
	if m != nil {
		return m.Clotho
	}
	return false
}

func (m *RoundEvent) GetAtropos() Trilean {
	if m != nil {
		return m.Atropos
	}
	return Trilean_UNDEFINED
}

type RoundInfoMessage struct {
	Events               map[string]*RoundEvent `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Queued               bool                   `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RoundInfoMessage) Reset()         { *m = RoundInfoMessage{} }
func (m *RoundInfoMessage) String() string { return proto.CompactTextString(m) }
func (*RoundInfoMessage) ProtoMessage()    {}
func (*RoundInfoMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_06add9379b5a2b9a, []int{1}
}

func (m *RoundInfoMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundInfoMessage.Unmarshal(m, b)
}
func (m *RoundInfoMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundInfoMessage.Marshal(b, m, deterministic)
}
func (m *RoundInfoMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundInfoMessage.Merge(m, src)
}
func (m *RoundInfoMessage) XXX_Size() int {
	return xxx_messageInfo_RoundInfoMessage.Size(m)
}
func (m *RoundInfoMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundInfoMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RoundInfoMessage proto.InternalMessageInfo

func (m *RoundInfoMessage) GetEvents() map[string]*RoundEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *RoundInfoMessage) GetQueued() bool {
	if m != nil {
		return m.Queued
	}
	return false
}

func init() {
	proto.RegisterEnum("poset.Trilean", Trilean_name, Trilean_value)
	proto.RegisterType((*RoundEvent)(nil), "poset.RoundEvent")
	proto.RegisterType((*RoundInfoMessage)(nil), "poset.RoundInfoMessage")
	proto.RegisterMapType((map[string]*RoundEvent)(nil), "poset.RoundInfoMessage.EventsEntry")
}

func init() { proto.RegisterFile("roundInfo.proto", fileDescriptor_06add9379b5a2b9a) }

var fileDescriptor_06add9379b5a2b9a = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0x49, 0xbe, 0xa4, 0xcd, 0x0d, 0xd6, 0x38, 0x0b, 0x09, 0xe2, 0xa2, 0xd4, 0x85,
	0x41, 0x30, 0x8b, 0xb8, 0x11, 0x5d, 0x95, 0x76, 0x0a, 0x85, 0xda, 0xc5, 0xd8, 0x3e, 0x40, 0xa4,
	0xd7, 0x3f, 0x18, 0xe6, 0xc6, 0xcc, 0xa4, 0xd0, 0x07, 0xf3, 0xfd, 0x24, 0x93, 0x04, 0x8b, 0xbb,
	0xb9, 0x73, 0xce, 0x6f, 0xce, 0xb9, 0x03, 0xa7, 0x15, 0xd5, 0x6a, 0xb7, 0x54, 0xaf, 0x94, 0x96,
	0x15, 0x19, 0xe2, 0x5e, 0x49, 0x1a, 0xcd, 0xa4, 0x00, 0x90, 0x8d, 0x22, 0xf6, 0xa8, 0x0c, 0xbf,
	0x84, 0x60, 0x46, 0x4a, 0xa3, 0xd2, 0xb5, 0x8e, 0xd9, 0x98, 0x25, 0x43, 0xf9, 0x7b, 0xc1, 0xcf,
	0xc1, 0x9f, 0x15, 0x64, 0xde, 0x29, 0x76, 0xac, 0xd4, 0x4d, 0x3c, 0x81, 0xc1, 0xd4, 0x54, 0x54,
	0x92, 0x8e, 0xdd, 0x31, 0x4b, 0x46, 0xd9, 0x28, 0xb5, 0x8f, 0xa7, 0x9b, 0xea, 0xa3, 0xc0, 0x5c,
	0xc9, 0x5e, 0x9e, 0x7c, 0x33, 0x88, 0x64, 0x5f, 0xe4, 0x09, 0xb5, 0xce, 0xdf, 0x90, 0x3f, 0x82,
	0x6f, 0xd3, 0x9b, 0x44, 0x37, 0x09, 0xb3, 0xab, 0x8e, 0xfe, 0x6b, 0x4c, 0x5b, 0x97, 0x50, 0xa6,
	0x3a, 0xc8, 0x0e, 0x69, 0x3a, 0x7d, 0xd5, 0x58, 0xe3, 0xae, 0xef, 0xd4, 0x4e, 0x17, 0x2b, 0x08,
	0x8f, 0xec, 0x3c, 0x02, 0xf7, 0x13, 0x0f, 0x76, 0xa5, 0x40, 0x36, 0x47, 0x7e, 0x0d, 0xde, 0x3e,
	0x2f, 0x6a, 0xb4, 0x5c, 0x98, 0x9d, 0x1d, 0x87, 0x5a, 0x52, 0xb6, 0xfa, 0x83, 0x73, 0xcf, 0x6e,
	0x6e, 0x61, 0xd0, 0xed, 0xc2, 0x4f, 0x20, 0xd8, 0xae, 0xe7, 0x62, 0xb1, 0x5c, 0x8b, 0x79, 0xf4,
	0x8f, 0x0f, 0xe1, 0xff, 0x46, 0x6e, 0x45, 0xc4, 0x78, 0x00, 0xde, 0x62, 0xba, 0x7a, 0x16, 0x91,
	0xf3, 0xe2, 0xdb, 0x2f, 0xbe, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xd2, 0x19, 0x29, 0x75,
	0x01, 0x00, 0x00,
}
