// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ctrl.proto

package wire

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IDResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDResponse) Reset()         { *m = IDResponse{} }
func (m *IDResponse) String() string { return proto.CompactTextString(m) }
func (*IDResponse) ProtoMessage()    {}
func (*IDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0572e205f89e843, []int{0}
}

func (m *IDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDResponse.Unmarshal(m, b)
}
func (m *IDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDResponse.Marshal(b, m, deterministic)
}
func (m *IDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDResponse.Merge(m, src)
}
func (m *IDResponse) XXX_Size() int {
	return xxx_messageInfo_IDResponse.Size(m)
}
func (m *IDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IDResponse proto.InternalMessageInfo

func (m *IDResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StakeResponse struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakeResponse) Reset()         { *m = StakeResponse{} }
func (m *StakeResponse) String() string { return proto.CompactTextString(m) }
func (*StakeResponse) ProtoMessage()    {}
func (*StakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0572e205f89e843, []int{1}
}

func (m *StakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeResponse.Unmarshal(m, b)
}
func (m *StakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeResponse.Marshal(b, m, deterministic)
}
func (m *StakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeResponse.Merge(m, src)
}
func (m *StakeResponse) XXX_Size() int {
	return xxx_messageInfo_StakeResponse.Size(m)
}
func (m *StakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StakeResponse proto.InternalMessageInfo

func (m *StakeResponse) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type InternalTxnRequest struct {
	Amount               uint64   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalTxnRequest) Reset()         { *m = InternalTxnRequest{} }
func (m *InternalTxnRequest) String() string { return proto.CompactTextString(m) }
func (*InternalTxnRequest) ProtoMessage()    {}
func (*InternalTxnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0572e205f89e843, []int{2}
}

func (m *InternalTxnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalTxnRequest.Unmarshal(m, b)
}
func (m *InternalTxnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalTxnRequest.Marshal(b, m, deterministic)
}
func (m *InternalTxnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalTxnRequest.Merge(m, src)
}
func (m *InternalTxnRequest) XXX_Size() int {
	return xxx_messageInfo_InternalTxnRequest.Size(m)
}
func (m *InternalTxnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalTxnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalTxnRequest proto.InternalMessageInfo

func (m *InternalTxnRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InternalTxnRequest) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func init() {
	proto.RegisterType((*IDResponse)(nil), "wire.IDResponse")
	proto.RegisterType((*StakeResponse)(nil), "wire.StakeResponse")
	proto.RegisterType((*InternalTxnRequest)(nil), "wire.InternalTxnRequest")
}

func init() { proto.RegisterFile("ctrl.proto", fileDescriptor_a0572e205f89e843) }

var fileDescriptor_a0572e205f89e843 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x93, 0xd0, 0x16, 0x1d, 0x51, 0x64, 0x94, 0x12, 0xa2, 0x07, 0x59, 0x10, 0x3c, 0x6d,
	0x45, 0xc1, 0xbb, 0x50, 0xc1, 0x1c, 0xbc, 0xac, 0xbe, 0xc0, 0xb6, 0x1d, 0x43, 0x30, 0xd9, 0x8d,
	0x9b, 0xd9, 0xaa, 0x8f, 0xe6, 0xdb, 0x49, 0x77, 0x6b, 0x55, 0xa4, 0xc7, 0x7f, 0xf8, 0x66, 0xe6,
	0xff, 0x00, 0xe6, 0xec, 0x1a, 0xd9, 0x39, 0xcb, 0x16, 0x07, 0x6f, 0xb5, 0xa3, 0xe2, 0xa4, 0xb2,
	0xb6, 0x6a, 0x68, 0x12, 0x66, 0x33, 0xff, 0x3c, 0xa1, 0xb6, 0xe3, 0x8f, 0x88, 0x88, 0x53, 0x80,
	0x72, 0xaa, 0xa8, 0xef, 0xac, 0xe9, 0x09, 0x0f, 0x20, 0xab, 0x17, 0x79, 0x7a, 0x96, 0x5e, 0xec,
	0xaa, 0xac, 0x5e, 0x88, 0x73, 0xd8, 0x7f, 0x64, 0xfd, 0x42, 0x1b, 0xe0, 0x18, 0x86, 0x4b, 0xdd,
	0x78, 0x0a, 0x4c, 0xaa, 0x62, 0x10, 0xf7, 0x80, 0xa5, 0x61, 0x72, 0x46, 0x37, 0x4f, 0xef, 0x46,
	0xd1, 0xab, 0xa7, 0x9e, 0x71, 0x0c, 0x23, 0xdd, 0x5a, 0x6f, 0x38, 0xc0, 0x03, 0xb5, 0x4e, 0x58,
	0xc0, 0x8e, 0xa3, 0x39, 0xd5, 0x4b, 0x72, 0x79, 0x16, 0x5e, 0x6d, 0xf2, 0xd5, 0x67, 0x0a, 0xf0,
	0xa0, 0x8d, 0xae, 0xa8, 0x25, 0xc3, 0x78, 0x09, 0x59, 0x39, 0xc5, 0xb1, 0x8c, 0x06, 0xf2, 0xdb,
	0x40, 0xde, 0xad, 0x0c, 0x8a, 0x43, 0xb9, 0xf2, 0x93, 0x3f, 0xfd, 0x45, 0x82, 0x37, 0x30, 0x0c,
	0x8d, 0xb7, 0x2e, 0x1d, 0xc5, 0xa5, 0x3f, 0x5a, 0x22, 0xc1, 0x5b, 0xd8, 0xfb, 0xa5, 0x80, 0xf9,
	0xfa, 0xf4, 0x3f, 0xab, 0x62, 0xcb, 0x5d, 0x91, 0xcc, 0x46, 0x61, 0x72, 0xfd, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x06, 0x33, 0xbf, 0xb8, 0x82, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagementClient is the client API for Management service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagementClient interface {
	ID(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*IDResponse, error)
	Stake(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StakeResponse, error)
	InternalTxn(ctx context.Context, in *InternalTxnRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type managementClient struct {
	cc *grpc.ClientConn
}

func NewManagementClient(cc *grpc.ClientConn) ManagementClient {
	return &managementClient{cc}
}

func (c *managementClient) ID(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*IDResponse, error) {
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, "/wire.Management/ID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementClient) Stake(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StakeResponse, error) {
	out := new(StakeResponse)
	err := c.cc.Invoke(ctx, "/wire.Management/Stake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementClient) InternalTxn(ctx context.Context, in *InternalTxnRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/wire.Management/InternalTxn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServer is the server API for Management service.
type ManagementServer interface {
	ID(context.Context, *empty.Empty) (*IDResponse, error)
	Stake(context.Context, *empty.Empty) (*StakeResponse, error)
	InternalTxn(context.Context, *InternalTxnRequest) (*empty.Empty, error)
}

func RegisterManagementServer(s *grpc.Server, srv ManagementServer) {
	s.RegisterService(&_Management_serviceDesc, srv)
}

func _Management_ID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServer).ID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wire.Management/ID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServer).ID(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Management_Stake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServer).Stake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wire.Management/Stake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServer).Stake(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Management_InternalTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServer).InternalTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wire.Management/InternalTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServer).InternalTxn(ctx, req.(*InternalTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Management_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wire.Management",
	HandlerType: (*ManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ID",
			Handler:    _Management_ID_Handler,
		},
		{
			MethodName: "Stake",
			Handler:    _Management_Stake_Handler,
		},
		{
			MethodName: "InternalTxn",
			Handler:    _Management_InternalTxn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ctrl.proto",
}
