name: Check build

on: [push]

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Golang dependency
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Build
        run: make opera && chmod +x ./build/opera

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: opera
          path: ./build/opera
